# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4da8cc97b341f35f72d2e201e67e8bbff849bbe915783277777b86ca2cca852f6b5163a0af54ed1976af63c3d3ffb7f242ac1f051b87224f6155b3482fbf0eb5

test:
  secret_key_base: 2942833f243ea8eab3d26a4cd98130c7700596dd7051255887679ef684f8b7f448d5aaad151ecd2138c44cccc04c775c357c83699aaaa61ed24642bb9f29d38f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
